// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3550.Mihai2018.commands;
import org.usfirst.frc3550.Mihai2018.Robot;

//import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

//public final float INCHES2MM = 25.4;


/**
 *
 */
public class PosXColorXObjAutolineCommand extends CommandGroup {

    public PosXColorXObjAutolineCommand() {
    	
    	requires(Robot.driveTrain);
    	
    	//System.out.println("Running PosXColorXObjAutolineCommand");
    	//addSequential(new DriveDistanceCommand(120, 1)); // 1 = Forward
    	
    	addSequential(new Autoline());
    }

}
